language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
# command to install dependencies
install: pip install -r build_requirements.txt
# command to run tests
script:
    - python setup.py bdist_egg
    - python setup.py test
    - pep8 loremipsum
    - pylint -E --rcfile .pylintrc loremipsum
    - python setup.py build_sphinx
